export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SET_USER = 'SET_USER'
export const ADD_BOOKMARKED_PROJECT = 'ADD_BOOKMARKED_PROJECT'
export const SET_HTTP_CLIENT_AUTH_TOKEN = 'SET_HTTP_CLIENT_AUTH_TOKEN'
