export const SET_PROJECTS = 'SET_PROJECTS'
export const SET_PROJECT = 'SET_PROJECT'
export const ADD_PROJECT_FEEDBACK_ENTRY = 'ADD_PROJECT_FEEDBACK_ENTRY'
export const UPDATE_PROJECT_FEEDBACK_ENTRY = 'UPDATE_PROJECT_FEEDBACK_ENTRY'
